export const logoMap: Record<string, string> = {
  "Займер": "/logos/imgi_2_zaymer.svg",
  eKapusta: "/logos/imgi_1_eKapusta.svg",
  MoneyMan: "/logos/imgi_13_moneyman.svg",
  "Joy Money": "/logos/imgi_8_joy.money.svg",
  Ezaem: "/logos/imgi_10_ezaem.svg",
  Creditter: "/logos/imgi_12_creditter.svg",
  Webbankir: "/logos/official_webbankir.png",
  Webzaim: "/logos/imgi_16_webzaim.svg",
  Vivus: "/logos/imgi_19_vivus.svg",
  Platiza: "/logos/imgi_20_platiza.svg",
  OneClickMoney: "/logos/imgi_25_oneclickmoney.svg",
  GreenMoney: "/logos/imgi_28_greenmoney.svg",
  MigCredit: "/logos/official_migcredit.png",
  Деньга: "/logos/imgi_32_denga.svg",
  FastMoney: "/logos/official_fastmoney.png",
  Kviku: "/logos/official_kviku.png",
  TurboZaim: "/logos/imgi_39_turbozaim.svg",
  Finterra: "/logos/imgi_41_finterra.svg",
  CarMoney: "/logos/imgi_48_carmoney.svg",
  Moneza: "/logos/imgi_49_moneza.svg",
  SmsFinance: "/logos/imgi_51_smsfinance.svg",
  "Деньги Сразу": "/logos/official_dengisrazu.png",
  BelkaCredit: "/logos/official_belkacredit.png",
  Adengi: "/logos/official_adengi.png",
  "495 Кредит": "/logos/official_495credit.svg",
  BeriBeru: "/logos/official_beriberu.png",
  "Max Credit - Выдача": "/logos/official_maxcredit.png",
  "OneClickMoney (micro)": "/logos/imgi_25_oneclickmoney.svg",
  "Привет, сосед": "/logos/official_privsosed.png",
  "Свои люди": "/logos/imgi_45_svoi-ludi.svg",
  "БЫСТРО ДЕНЬГИ": "/logos/official_bistrodengi.png",
  "Ваш Кредит - Выдача": "/logos/imgi_38_vash-kredit.svg",
  НЕБУС: "/logos/imgi_34_nebusfinance.svg",
  Finters: "/logos/imgi_63_finters-1.svg",
  Boostra: "/logos/official_boostra.svg",
  Cashmagnit: "/logos/official_cashmagnit.svg",
  CashToYou: "/logos/placeholder_cashtoyou.svg",
  Credit7: "/logos/official_credit7.png",
  Fin5: "/logos/official_fin5.png",
  "Fresh Zaim": "/logos/placeholder_freshzaim.svg",
  Rocketman: "/logos/official_rocketman.svg",
  "Альфа Деньги (нерезиденты)": "/logos/imgi_65_alfabank.svg",
  "Альфа Деньги - Кредитный лимит": "/logos/imgi_65_alfabank.svg",
  "Бережный - МФО Выдача": "/logos/official_berezhny.svg",
  ДеньгиОК: "/logos/imgi_11_dengiok.svg",
  "До Зарплаты": "/logos/imgi_73_dozarplati.svg",
  ДоброЗайм: "/logos/official_dobrozaim.png",
  ДрайвЗайм: "/logos/official_drivezaim.png",
  Капиталина: "/logos/imgi_55_capitalina.svg",
  ЛайкЗайм: "/logos/official_likezaim.svg",
  ЛигаМФО: "/logos/official_ligamfo.png",
  Микроклад: "/logos/official_microklad.png",
  "МультиЗайм (привязка карты)": "/logos/official_multizaim.svg",
  "Простой вопрос": "/logos/official_prostovopros.png",
  "Срочно деньги": "/logos/official_srochnodengi.svg",
  "У Абрамовича": "/logos/official_uabramovicha.png",
  ФинМолл: "/logos/placeholder_finmoll.svg",
  Центрофинанс: "/logos/official_centrofinans.png",
  "Т-Банк - Кредитная карта Платинум": "/logos/official_tbank.png",
  "Уралсиб - Кредитная карта 120 дней без %": "/logos/official_uralsib.svg",
  "Уралсиб - Кредитная карта с кешбэком": "/logos/official_uralsib.svg",
};
