export const logoMap: Record<string, string> = {
  "Займер": "/logos/imgi_2_zaymer.svg",
  eKapusta: "/logos/imgi_1_eKapusta.svg",
  MoneyMan: "/logos/imgi_13_moneyman.svg",
  "Joy Money": "/logos/imgi_8_joy.money.svg",
  Ezaem: "/logos/imgi_10_ezaem.svg",
  Creditter: "/logos/imgi_12_creditter.svg",
  Webbankir: "/logos/imgi_17_webbankir.svg",
  Webzaim: "/logos/imgi_16_webzaim.svg",
  Vivus: "/logos/imgi_19_vivus.svg",
  Platiza: "/logos/imgi_20_platiza.svg",
  OneClickMoney: "/logos/imgi_25_oneclickmoney.svg",
  GreenMoney: "/logos/imgi_28_greenmoney.svg",
  MigCredit: "/logos/imgi_30_migcredit_1.svg",
  Деньга: "/logos/imgi_32_denga.svg",
  FastMoney: "/logos/imgi_36_fastmoney.svg",
  Kviku: "/logos/imgi_37_kviku.svg",
  TurboZaim: "/logos/imgi_39_turbozaim.svg",
  Finterra: "/logos/imgi_41_finterra.svg",
  CarMoney: "/logos/imgi_48_carmoney.svg",
  Moneza: "/logos/imgi_49_moneza.svg",
  SmsFinance: "/logos/imgi_51_smsfinance.svg",
  "Деньги Сразу": "/logos/imgi_52_dehgi-srazy.svg",
  BelkaCredit: "/logos/imgi_53_belkacredit.svg",
  Adengi: "/logos/imgi_74_adengi.svg",
};
