import Link from "next/link";
import { ArrowRight, BadgeCheck, CircleAlert } from "lucide-react";
import { categorySlug, offerCategories, type Offer } from "@/lib/catalog";

export default function Offers({ offers }: { offers: Offer[] }) {
  const categories = offerCategories(offers);
  return <section id="offers" className="bg-slate-50 py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="inline-flex rounded-full bg-blue-100 px-4 py-2 text-sm font-bold text-blue-700">Каталог</span><h2 className="mt-5 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">Финансовые продукты</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Опубликованные предложения из каталога партнёров.</p></div><Link href="/products" className="inline-flex items-center gap-2 text-sm font-bold text-blue-700 transition hover:translate-x-1 hover:text-blue-800">Открыть весь каталог <ArrowRight size={16} aria-hidden="true" /></Link></div>
    {offers.length > 0 ? <div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{offers.slice(0, 3).map((offer) => <article key={offer.id} className="rounded-[1.75rem] border border-slate-200 bg-white p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-2xl hover:shadow-blue-950/10"><div className="flex items-start justify-between gap-4"><span className="text-sm font-bold text-blue-700">{offer.company}</span>{offer.badge && <span className="rounded-full bg-green-100 px-3 py-1 text-xs font-bold text-green-700">{offer.badge}</span>}</div><h3 className="mt-5 text-2xl font-black tracking-tight text-slate-950">{offer.productName || offer.company}</h3>{offer.description && <p className="mt-3 text-sm leading-6 text-slate-600">{offer.description}</p>}<a href={offer.affiliateUrl} target="_blank" rel="noreferrer sponsored" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-blue-700 transition hover:translate-x-1 hover:text-blue-800">Перейти к условиям <ArrowRight size={16} aria-hidden="true" /></a></article>)}</div> : <div className="mt-10 rounded-[1.75rem] border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-7 shadow-sm"><div className="flex gap-4"><CircleAlert className="mt-0.5 shrink-0 text-blue-700" aria-hidden="true" /><div><h3 className="font-bold text-slate-900">Предложения обновляются</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">В публичном каталоге пока нет опубликованных программ.</p></div></div></div>}
    {categories.length > 0 && <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.map((category) => <Link key={category.slug} href={`/${categorySlug(category.name)}`} className="group flex items-center justify-between rounded-2xl border border-slate-200 bg-white px-5 py-5 shadow-sm transition duration-300 hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-950/8"><span><span className="block font-bold text-slate-900">{category.name}</span><span className="mt-1.5 block text-sm leading-5 text-slate-500">Опубликованные предложения категории.</span></span><BadgeCheck className="ml-4 shrink-0 text-blue-600 transition group-hover:scale-110" size={20} aria-hidden="true" /></Link>)}</div>}
  </div></section>;
}
